import numpy as np
a=np.array([[1,3,5],[7,9,11],[13,15,17]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=np.dot(a,b)
print("matrix a:")
print(a)
print("\n matrix b:")
print(b)
print("\n multiplication result (a*b):")
print(result)
